### ISSUE TITLE
Support <U+0A02 BINDI, U+0A40 VOWEL SIGN II>

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gurmukhi#23]
### Fonts
NotoSansGurmukhi-Regular.otf
NotoSerifGurmukhi-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/gurmukhi/releases/tag/NotoSansGurmukhi-v2.003
Site: https://github.com/notofonts/gurmukhi/releases/tag/NotoSerifGurmukhi-v2.003
Date: 2022-12-25

### Font version
Version 2.003

### Issue
The Noto fonts should support the sequence <U+0A02, U+0A40>, [as newly specified in <i>The Unicode Standard, Version 15.0</i>](https://www.unicode.org/versions/Unicode15.0.0/ch12.pdf#page=38):
> <b><i>Unusual Positioning of </i>bindi<i>.</i></b> Typically, when U+0A40 GURMUKHI VOWEL SIGN II and U+0A02 GURMUKHI SIGN BINDI coexist in an orthographic syllable, the <i>bindi</i> is encoded after and rendered on the right side of the <i>vowel sign ii</i>. In cases where a special left side placement of the <i>bindi</i> must be distinguished in encoding, the <i>bindi</i> can be encoded immediately preceding the <i>vowel sign ii</i> instead.

In the current versions of the fonts, the bindi overlaps the vowel sign.

### Character data
ੲਂੀ
U+0A72 GURMUKHI IRI
U+0A02 GURMUKHI SIGN BINDI
U+0A40 GURMUKHI VOWEL SIGN II

### Screenshots
![ੲਂੀ](https://user-images.githubusercontent.com/1124347/209489165-ca9a38db-c609-4db1-8a4a-8369125f3c1e.png)
![ੲਂੀ](https://user-images.githubusercontent.com/1124347/209489205-b8882ab7-4083-4b87-8556-c219b9ad72e6.png)

**Comment by simoncozens** [comment]
I've fixed this (in an admittedly simple way). Note that this syllable formation is not supported in CoreText yet, so it will give a dotted circle on Apple software. Once CoreText fixes their syllable definitions, the font will work there too.
