### ISSUE TITLE
La ha-ha versus la-ha ha conjunct

### ISSUE THREAD

**Issue by simoncozens** [notofonts/gurmukhi#5]
As reported by John in #1, the word ਓਲ੍ਹ੍ਹਗੀ forms a conjunct "la ha-ha" whereas other fonts handle it as "la-ha ha". Is this OK? Do we want to change it?
![shape](https://user-images.githubusercontent.com/106728/175062830-08863222-f398-4498-85a5-985d20387493.png)

**Comment by simoncozens** [comment]
Maybe let's not change it then unless there's significant user feedback.

**Comment by satnamsvirdi** [comment]
Regarding shared image, I'd say that it looks weird. It must create a half ha underneath la but if someone adds halant after that, it must retain the first half-ha and must not create any half form after that for same consonant.

![Group](https://user-images.githubusercontent.com/15929121/221369306-9ad276b4-670d-4c23-9757-f1879736812f.png)
Just ignore the space between letters. This would be ideal IMO. Your thoughts?

**Comment by tiroj** [comment]
Have we confirmed that this word, or ones involving this kind of sequence, _actually exist_? I have found ਓਲ੍ਹ੍ਹਗੀਆ — i.e. without the second halanta — in the Sikh scriptures and elsewhere, but not spelled as in this issue.

**Comment by satnamsvirdi** [comment]
Practically, as far as I know, you will never encounter this kind of word in Punjabi. In modern Punjabi, even the experts are trying to reduce the usage of half-forms.

I searched for ਓਲ੍ਹ੍ਹਗੀਆ in Google and found a result in [GuruGranthDarpan.net](https://www.gurugranthdarpan.net/0421.html) for this word. But I noticed something weird there.

They are using half-ha but the shape of the glyph rendered on the screen by the font suggests that they want to use Udaat (U+0A51) there. 

So technically, the right spelling would be ਓਲੑਗੀਆ, not ਓਲ੍ਹਗੀਆ. Here, usage of udaat is to indicate high-tone (uccha swar - ਉੱਚਾ ਸੁਰ) of the letter.

<img width="211" alt="Screenshot 2023-02-26 at 1 19 27 PM" src="https://user-images.githubusercontent.com/15929121/221399424-18ead7b5-9bf6-4b7f-ae29-6aed37a1c436.png">

One result I found in [here](https://www.gurbanifiles.net/unicode/index.htm) which can solve our problem. Seems like font developer used a hack to make typing of Udaat easier as there is no direct key on Windows to type udaat and yaksh. On Mac however, I discovered today that there's a key for Udaat/Yaksha but not is not widely popular among most of the Punjabi users.

Summarising, there is no word in Punjabi or Sikh scriptures which uses double half-ha as of now.

**Comment by tiroj** [comment]
Yes, it looks like some fonts are using a glyph level hack to display halanta+ha+halanta as udaat. Oof! That’s a really bad idea.

**Comment by tiroj** [comment]
Have also found live examples of the similar hack to represent the yakash sign using halanta+ya+halanta+ya in ਮਿਥ੍ਯ੍ਯੰਤ (ਮਿਥੵੰਤ). These include https://www.gurugranthdarpan.net/1354.html but also other sites, indicating that these hacks may have proliferated among users dependent on the hack fonts.
